In [7]:
import pandas as pd 
import numpy as np

In [ ]:
pd.read_csv ('canais_venda.csv', sep=';')
pd.read_csv ('clientes.csv', sep=';')
pd.read_csv ('funcionarios.csv', sep=';')
pd.read_csv ('reservas.csv', sep=';')
pd.read_csv ('tipos_quarto.csv', sep=';')
pd.read_csv ('unidades.csv', sep=';')

In [71]:
df = pd.read_csv('unidades.csv', sep=';')

print(df.shape)
display(df.head())
display(df.tail())
display(df.dtypes)

(12, 6)

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
0,1,NaraHoteis Ipanema,Rio de Janeiro,Capital,5 estrelas,80.0
1,2,NaraHoteis Barra da Tijuca,Rio de Janeiro,capital,4 estrelas,120.0
2,3,NaraHoteis Centro,Rio de Janeiro,Capital,3*,60.0
3,4,NaraHoteis Santa Teresa,Rio de Janeiro,CAP,4 estrelas,45.0
4,5,NaraHoteis Nova Iguaçu Centro,Nova Iguaçu,Baixada Fluminense,Três Estrelas,50.0

,id_unidade,nome_unidade,cidade,regiao,categoria_hotel,num_quartos_total
7,8,NaraHoteis Teresópolis,Teresópolis,Serra,4 Estrelas,60.0
8,9,NaraHoteis Friburgo,Nova Friburgo,Serra,4 estrelas,55.0
9,10,NaraHoteis Paraty,Paraty,Costa Verde,5 estrelas,NaN
10,11,NaraHoteis Angra dos Reis,Angra dos Reis,Costa Verde,cinco estrelas,90.0
11,12,NaraHoteis Mangaratiba,Mangaratiba,Costa Verde,4 estrelas,50.0

id_unidade             int64
nome_unidade             str
cidade                   str
regiao                   str
categoria_hotel          str
num_quartos_total    float64
dtype: object

In [75]:
df.duplicated(subset=['num_quartos_total'  ]).sum()

np.int64(4)

In [76]:
df[df.duplicated(subset=['num_quartos_total'], keep=False)].sort_values(by='nome')

KeyError: 'nome'

In [ ]:
df['nome'].value_counts()

In [70]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [id_tipo_quarto, descricao, capacidade_max, valor_diaria_base]
Index: []

CSV CANAIS DE VENDA

(p)coluna canal de venda tem 'ota' o que seria?
(t)coluna comissão pct esta em str


CSV CLIENTE

(t) clientes duplicados (3?)
(p) temos clientes com todas as informações idênticas salvo coluna de estado de origem 

(t) coluna de tipo de cliente precisa ser padroni.
(p) NaN existente, não deveria constar como nulo?
(t) coluna estado de origem tem que ser padroni.
(p) coluna faixa_etaria com muito NaN PERGUNTA DE NEGOCIO, É IMPORTANTE PARA A LEITURA DO NEGOCIO


CSV FUNCIONARIO

(t) Coluna salatio str
(p) coluna salario 6 NaN IMPORTANTE PARA A LEITURA?
(t) leta maiuscula na coluna cargo


CSV RESERVAS

(t) Coluna status reserva precisa ser padronizado
(t) NaN na coluna id_canal e avaliação_ cliente IMPORTANTE PARA LEITURA
(t) Coluna forma de pagamento precisa padronizar

CSV tipos quarto

(t) coluna valor diaria base como str


CSV UNIDADES

(t) regiao precisa padronizar espaço no serra
(t) categoria hotel padronizar, nome ext. str
(t) numero de quartos esta float precisa ir para int